export const presetFakeSchema = [
    { value: 'name', label: 'Full Name' },
    { value: 'firstName', label: 'First Name' },
    { value: 'lastName', label: 'Last Name' },
    { value: 'email', label: 'Email Address' },
    { value: 'phoneNumber', label: 'Phone Number' },
    { value: 'address', label: 'Full Address' },
    { value: 'city', label: 'City' },
    { value: 'country', label: 'Country' },
    { value: 'zipCode', label: 'Zip Code' },
    { value: 'company', label: 'Company Name' },
    { value: 'jobTitle', label: 'Job Title' },
    { value: 'bs', label: 'Business Slogan' },
    { value: 'catchPhrase', label: 'Catch Phrase' },
    { value: 'uuid4', label: 'UUID' },
    { value: 'word', label: 'Single Word' },
    { value: 'sentence', label: 'Sentence' },
    { value: 'paragraph', label: 'Paragraph' },
];